=== Chemotion/chemotionapi/tests/schemas/layer/draft-01.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "chemotion://generic/layer/draft-01",
    "title": "Schema for generic layer",
    "type": "object",
    "properties": {
        "wf": {
            "type": "boolean"
        },
        "key": {
            "type": "string",
            "pattern": "^[a-z][a-zA-Z_]{1,20}[a-z]$"
        },
        "cols": {
            "type": "number"
        },
        "color": {
            "type": "string",
            "enum": [
                "none",
                "primary",
                "info",
                "success",
                "default",
                "danger",
                "warning"
            ]
        },
        "label": {
            "type": "string"
        },
        "style": {
            "type": "string",
            "pattern": "^panel_generic_heading$|^panel_generic_heading_([bui])(?!.*\u0001)([bui])?(?!.*\u0001|.*\u0002)([bui])?$"
        },
        "fields": {
            "type": "array",
            "items": {
                "$ref": "chemotion://generic/field/draft-01"
            }
        },
        "position": {
            "type": "number",
            "minimum": 1
        },
        "timeRecord": {
            "type": "string"
        },
        "cond_fields": {
            "type": "array",
            "items": {
                "$ref": "chemotion://generic/cond_field/draft-01"
            }
        },
        "wf_position": {
            "type": "number",
            "minimum": 0
        },
        "cond_operator": {
            "type": "number",
            "enum": [
                9,
                1,
                0
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "wf",
        "key",
        "cols",
        "color",
        "label",
        "style",
        "fields",
        "position",
        "timeRecord",
        "wf_position"
    ]
}

=== Chemotion/chemotionapi/a.json
{
  "wf": false,
  "key": "aaa",
  "cols": 3,
  "color": "none",
  "label": "bbb",
  "style": "panel_generic_heading",
  "fields": [
    {
      "cols": 2,
      "type": "checkbox",
      "field": "a",
      "label": "a",
      "default": "",
      "position": 1,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "datetime",
      "field": "b",
      "label": "b",
      "default": "",
      "position": 2,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "datetime-range",
      "field": "c",
      "label": "c",
      "default": "",
      "position": 3,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "drag_element",
      "field": "d",
      "label": "d",
      "default": "",
      "position": 4,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "drag_molecule",
      "field": "e",
      "label": "e",
      "default": "",
      "position": 5,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "drag_sample",
      "field": "f",
      "label": "f",
      "default": "",
      "position": 6,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "formula-field",
      "field": "g",
      "label": "g",
      "decimal": "2",
      "default": "",
      "formula": "i*3",
      "position": 7,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "input-group",
      "field": "h",
      "label": "h",
      "default": "",
      "position": 8,
      "required": false,
      "sub_fields": [
        {
          "id": "c69acf5c-50ff-45c3-afe7-5e208fa0a245",
          "type": "number",
          "value": "1"
        },
        {
          "id": "fbe90755-8da0-426e-8591-b1143f5b1488",
          "type": "label",
          "value": ""
        },
        {
          "id": "dd4764e0-c7c7-47b5-a6c5-0df86c1082f0",
          "type": "text",
          "value": ""
        },
        {
          "id": "9c357be0-6c58-4a2a-b909-7845f2803129",
          "type": "system-defined",
          "value": "",
          "value_system": "eV",
          "option_layers": "energy"
        }
      ],
      "text_sub_fields": []
    },
    {
      "type": "integer",
      "field": "i",
      "label": "i",
      "default": "",
      "position": 9,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "select",
      "field": "j",
      "label": "j",
      "default": "",
      "position": 10,
      "required": false,
      "sub_fields": [],
      "option_layers": "aaa",
      "text_sub_fields": []
    },
    {
      "type": "system-defined",
      "field": "k",
      "label": "k",
      "default": "",
      "position": 11,
      "required": false,
      "sub_fields": [],
      "value_system": "rpm",
      "option_layers": "agitation",
      "text_sub_fields": []
    },
    {
      "type": "table",
      "field": "l",
      "label": "l",
      "default": "",
      "position": 12,
      "required": false,
      "sub_fields": [
        {
          "id": "639d2333-d364-4bc2-846e-517905f98aaa",
          "type": "drag_molecule",
          "value": "inchikey;smiles;iupac;molecular_weight;",
          "col_name": ""
        },
        {
          "id": "e8577d01-df93-4379-bb83-18bfebc00758",
          "type": "drag_sample",
          "value": "name;external_label;molecular_weight;",
          "col_name": ""
        },
        {
          "id": "0e8de19c-1daf-49b7-8884-7c7052da2903",
          "type": "select",
          "value": "",
          "col_name": "",
          "option_layers": "aaa"
        },
        {
          "id": "005d7d4e-7af0-44bd-a3ad-74c48f7b3798",
          "type": "system-defined",
          "value": "",
          "col_name": "",
          "value_system": "u_l",
          "option_layers": "enzyme_activity"
        },
        {
          "id": "42b1895b-2deb-427b-81dc-b1324821b6ca",
          "type": "text",
          "value": "",
          "col_name": ""
        }
      ],
      "text_sub_fields": []
    },
    {
      "type": "text",
      "field": "m",
      "label": "m",
      "default": "",
      "position": 13,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "text-formula",
      "field": "n",
      "label": "n",
      "default": "",
      "position": 14,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": [
        {
          "id": "b03d89e4-3f06-4e90-930a-8b877b825d04",
          "field": "m",
          "layer": "aaa",
          "separator": "."
        },
        {
          "id": "139f00d7-2d05-49b6-86b5-c6baa92d9207",
          "field": "l[@@]42b1895b-2deb-427b-81dc-b1324821b6ca",
          "layer": "aaa",
          "separator": "."
        }
      ]
    },
    {
      "type": "textarea",
      "field": "o",
      "label": "o",
      "default": "",
      "position": 15,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": []
    },
    {
      "type": "upload",
      "field": "p",
      "label": "p",
      "default": "",
      "position": 16,
      "required": false,
      "sub_fields": [],
      "text_sub_fields": []
    }
  ],
  "position": 10,
  "timeRecord": "",
  "wf_position": 0
}
