=== Chemotion/chemotionapi/tests/schemas/dataset/draft-01.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": {
            "type": "number"
        },
        "uuid": {
            "type": [
                "string",
                "null"
            ]
        },
        "label": {
            "type": "string"
        },
        "desc": {
            "type": "string"
        },
        "properties_template": {
            "$ref": "chemotion://generic/dataset_properties/draft-01"
        },
        "properties_release": {
            "$ref": "chemotion://generic/dataset_properties/draft-01"
        },
        "is_active": {
            "type": "boolean"
        },
        "version": {
            "type": [
                "string",
                "null"
            ]
        },
        "place": {
            "type": "number"
        },
        "released_at": {
            "type": [
                "string",
                "null"
            ]
        },
        "identifier": {
            "type": [
                "string",
                "null"
            ]
        },
        "sync_time": {},
        "created_by": {
            "type": "number"
        },
        "updated_by": {
            "type": [
                "number",
                "null"
            ]
        },
        "created_at": {
            "type": "string"
        },
        "updated_at": {
            "type": "string"
        },
        "ols_term_id": {
            "type": "string"
        }
    },
    "additionalProperties": false,
    "required": [
        "id",
        "uuid",
        "label",
        "desc",
        "properties_template",
        "properties_release",
        "is_active",
        "version",
        "place",
        "released_at",
        "identifier",
        "sync_time",
        "created_by",
        "updated_by",
        "created_at",
        "updated_at",
        "ols_term_id"
    ],
    "$id": "chemotion://generic/dataset/draft-01",
    "title": "Schema for generic dataset"
}

=== Chemotion/chemotionapi/tests/fixtures/GenericDataset.json
{
    "id": 8,
    "uuid": null,
    "label": "thin-layer chromatography (TLC)",
    "desc": "thin-layer chromatography (TLC)",
    "properties_template": {
        "eln": {
            "version": "1.8.0",
            "base_revision": "7bd6a5d81",
            "current_revision": 0
        },
        "uuid": "9a9665e0-a38b-4f0f-9358-56b72a4056d1",
        "klass": "DatasetKlass",
        "layers": {},
        "select_options": {}
    },
    "properties_release": {},
    "is_active": false,
    "version": null,
    "place": 80,
    "released_at": null,
    "identifier": null,
    "sync_time": null,
    "created_by": 1,
    "updated_by": null,
    "created_at": "2024-01-23 13:44:01 UTC",
    "updated_at": "2024-01-23 13:44:01 UTC",
    "ols_term_id": "CHMO:0001007"
}
